public enum Provincia {
    JUJUY, FORMOSA, MISIONES, TUCUMAN, SANTA_FE, LA_RIOJA, CATAMARCA, SGO_ESTERO, CORRIENTES, CORDOBA, SAN_JUAN, SAN_LUIS, BUENOS_AIRES, LA_PAMPA, NEUQUEN, CHUBUT, SANTA_CRUZ, TIERRA_FUEGO, SALTA, RIO_NEGRO, CHACO, MENDOZA, ENTRE_RIOS
}
